[package]
name = "lsp-monkey"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonrpc-core = "18.0.0"
jsonrpc-stdio-server = "18.0.0"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }

