#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  anon_sym_let = 3,
  anon_sym_EQ = 4,
  anon_sym_return = 5,
  sym_integer = 6,
  anon_sym_true = 7,
  anon_sym_false = 8,
  sym_string = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LBRACE = 12,
  anon_sym_COLON = 13,
  anon_sym_RBRACE = 14,
  anon_sym_BANG = 15,
  anon_sym_DASH = 16,
  anon_sym_EQ_EQ = 17,
  anon_sym_BANG_EQ = 18,
  anon_sym_GT = 19,
  anon_sym_LT = 20,
  anon_sym_PLUS = 21,
  anon_sym_STAR = 22,
  anon_sym_SLASH = 23,
  anon_sym_if = 24,
  anon_sym_LPAREN = 25,
  anon_sym_RPAREN = 26,
  anon_sym_else = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym__statement = 30,
  sym_let_statement = 31,
  sym_return_statement = 32,
  sym_expression_statement = 33,
  sym__expression = 34,
  sym_literal = 35,
  sym_boolean = 36,
  sym_array = 37,
  sym_hash = 38,
  sym_prefix_operator = 39,
  sym_prefix_expression = 40,
  sym_infix_expression = 41,
  sym_if_expression = 42,
  sym__block = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_array_repeat1 = 45,
  aux_sym_hash_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string] = "string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_if] = "if",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_else] = "else",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym_return_statement] = "return_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym_literal] = "literal",
  [sym_boolean] = "boolean",
  [sym_array] = "array",
  [sym_hash] = "hash",
  [sym_prefix_operator] = "prefix_operator",
  [sym_prefix_expression] = "prefix_expression",
  [sym_infix_expression] = "infix_expression",
  [sym_if_expression] = "if_expression",
  [sym__block] = "_block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_hash_repeat1] = "hash_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string] = sym_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_else] = anon_sym_else,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym_literal] = sym_literal,
  [sym_boolean] = sym_boolean,
  [sym_array] = sym_array,
  [sym_hash] = sym_hash,
  [sym_prefix_operator] = sym_prefix_operator,
  [sym_prefix_expression] = sym_prefix_expression,
  [sym_infix_expression] = sym_infix_expression,
  [sym_if_expression] = sym_if_expression,
  [sym__block] = sym__block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_hash_repeat1] = aux_sym_hash_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_hash] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_infix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hash_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_condition = 2,
  field_consequence = 3,
  field_left = 4,
  field_name = 5,
  field_operator = 6,
  field_right = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 0},
    {field_right, 1},
  [2] =
    {field_value, 1},
  [3] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [6] =
    {field_name, 1},
    {field_value, 3},
  [8] =
    {field_condition, 2},
    {field_consequence, 5},
  [10] =
    {field_alternative, 9},
    {field_condition, 2},
    {field_consequence, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '!', 25,
        '"', 2,
        '(', 34,
        ')', 35,
        '*', 32,
        '+', 31,
        '-', 26,
        '/', 33,
        ':', 23,
        ';', 14,
        '<', 30,
        '=', 16,
        '>', 29,
        '[', 20,
        ']', 21,
        '{', 22,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 25,
        '"', 2,
        ')', 35,
        '*', 32,
        '+', 31,
        '-', 26,
        '/', 33,
        ':', 23,
        ';', 14,
        '<', 30,
        '=', 11,
        '>', 29,
        '[', 20,
        ']', 21,
        '{', 22,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '=') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(8);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(53),
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym_expression_statement] = STATE(37),
    [sym__expression] = STATE(43),
    [sym_literal] = STATE(43),
    [sym_boolean] = STATE(9),
    [sym_array] = STATE(9),
    [sym_hash] = STATE(9),
    [sym_prefix_operator] = STATE(27),
    [sym_prefix_expression] = STATE(43),
    [sym_infix_expression] = STATE(43),
    [sym_if_expression] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_string] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym__statement] = STATE(2),
    [sym_let_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym_expression_statement] = STATE(37),
    [sym__expression] = STATE(43),
    [sym_literal] = STATE(43),
    [sym_boolean] = STATE(9),
    [sym_array] = STATE(9),
    [sym_hash] = STATE(9),
    [sym_prefix_operator] = STATE(27),
    [sym_prefix_expression] = STATE(43),
    [sym_infix_expression] = STATE(43),
    [sym_if_expression] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(30),
    [anon_sym_return] = ACTIONS(33),
    [sym_integer] = ACTIONS(36),
    [anon_sym_true] = ACTIONS(39),
    [anon_sym_false] = ACTIONS(39),
    [sym_string] = ACTIONS(36),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(51),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym__statement] = STATE(5),
    [sym_let_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym_expression_statement] = STATE(37),
    [sym__expression] = STATE(43),
    [sym_literal] = STATE(43),
    [sym_boolean] = STATE(9),
    [sym_array] = STATE(9),
    [sym_hash] = STATE(9),
    [sym_prefix_operator] = STATE(27),
    [sym_prefix_expression] = STATE(43),
    [sym_infix_expression] = STATE(43),
    [sym_if_expression] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_string] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(54),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym__statement] = STATE(2),
    [sym_let_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym_expression_statement] = STATE(37),
    [sym__expression] = STATE(43),
    [sym_literal] = STATE(43),
    [sym_boolean] = STATE(9),
    [sym_array] = STATE(9),
    [sym_hash] = STATE(9),
    [sym_prefix_operator] = STATE(27),
    [sym_prefix_expression] = STATE(43),
    [sym_infix_expression] = STATE(43),
    [sym_if_expression] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_string] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym__statement] = STATE(2),
    [sym_let_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym_expression_statement] = STATE(37),
    [sym__expression] = STATE(43),
    [sym_literal] = STATE(43),
    [sym_boolean] = STATE(9),
    [sym_array] = STATE(9),
    [sym_hash] = STATE(9),
    [sym_prefix_operator] = STATE(27),
    [sym_prefix_expression] = STATE(43),
    [sym_infix_expression] = STATE(43),
    [sym_if_expression] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_string] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(58),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym_identifier] = ACTIONS(60),
    [anon_sym_SEMI] = ACTIONS(62),
    [sym_integer] = ACTIONS(62),
    [anon_sym_true] = ACTIONS(60),
    [anon_sym_false] = ACTIONS(60),
    [sym_string] = ACTIONS(62),
    [anon_sym_LBRACK] = ACTIONS(62),
    [anon_sym_RBRACK] = ACTIONS(62),
    [anon_sym_LBRACE] = ACTIONS(62),
    [anon_sym_COLON] = ACTIONS(62),
    [anon_sym_RBRACE] = ACTIONS(62),
    [anon_sym_BANG] = ACTIONS(60),
    [anon_sym_DASH] = ACTIONS(62),
    [anon_sym_EQ_EQ] = ACTIONS(62),
    [anon_sym_BANG_EQ] = ACTIONS(62),
    [anon_sym_GT] = ACTIONS(62),
    [anon_sym_LT] = ACTIONS(62),
    [anon_sym_PLUS] = ACTIONS(62),
    [anon_sym_STAR] = ACTIONS(62),
    [anon_sym_SLASH] = ACTIONS(60),
    [anon_sym_if] = ACTIONS(60),
    [anon_sym_RPAREN] = ACTIONS(62),
    [anon_sym_else] = ACTIONS(64),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(68), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [30] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(72), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [60] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(76), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [90] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(80), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(84), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(88), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(92), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [210] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(86), 5,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_if,
    ACTIONS(88), 15,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(100), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [274] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(86), 5,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_if,
    ACTIONS(88), 11,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [312] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(86), 5,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_if,
    ACTIONS(88), 13,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_RPAREN,
  [348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 6,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_if,
    ACTIONS(108), 16,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [378] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(110), 1,
      sym_identifier,
    ACTIONS(112), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      aux_sym_array_repeat1,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(34), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [427] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(110), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_RBRACK,
    STATE(23), 1,
      aux_sym_array_repeat1,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(34), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [476] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      aux_sym_hash_repeat1,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(42), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [525] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_hash_repeat1,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(42), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [574] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(131), 1,
      anon_sym_LBRACK,
    ACTIONS(134), 1,
      anon_sym_RBRACK,
    ACTIONS(136), 1,
      anon_sym_LBRACE,
    ACTIONS(142), 1,
      anon_sym_if,
    STATE(23), 1,
      aux_sym_array_repeat1,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(125), 2,
      sym_integer,
      sym_string,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(139), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(34), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [623] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_LBRACK,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    ACTIONS(165), 1,
      anon_sym_if,
    STATE(24), 1,
      aux_sym_hash_repeat1,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(148), 2,
      sym_integer,
      sym_string,
    ACTIONS(151), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(162), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(42), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [672] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(168), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(17), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [715] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(170), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(16), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [758] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(172), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(11), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [801] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(12), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [844] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(35), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [887] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(178), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(44), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [930] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(14), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [973] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(182), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(45), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [1016] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(184), 1,
      sym_identifier,
    STATE(27), 1,
      sym_prefix_operator,
    ACTIONS(13), 2,
      sym_integer,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(9), 3,
      sym_boolean,
      sym_array,
      sym_hash,
    STATE(46), 5,
      sym__expression,
      sym_literal,
      sym_prefix_expression,
      sym_infix_expression,
      sym_if_expression,
  [1059] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(190), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(186), 5,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_if,
    ACTIONS(188), 5,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1095] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(190), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(192), 5,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_BANG,
      anon_sym_if,
    ACTIONS(194), 5,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1131] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 6,
      anon_sym_let,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
    ACTIONS(196), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
  [1154] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_SEMI,
    ACTIONS(202), 6,
      anon_sym_let,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
    ACTIONS(200), 8,
      ts_builtin_sym_end,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
  [1179] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 6,
      anon_sym_let,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
    ACTIONS(206), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
  [1202] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 6,
      anon_sym_let,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
    ACTIONS(210), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
  [1225] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 6,
      anon_sym_let,
      anon_sym_return,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
    ACTIONS(214), 8,
      ts_builtin_sym_end,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
  [1247] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 4,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
    ACTIONS(220), 6,
      sym_integer,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
  [1265] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(222), 1,
      anon_sym_COLON,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(190), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1290] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(224), 1,
      anon_sym_SEMI,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(190), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1315] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(226), 1,
      anon_sym_SEMI,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(190), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1340] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(228), 1,
      anon_sym_SEMI,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(190), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1365] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(190), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1390] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym__block,
  [1400] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    STATE(57), 1,
      sym__block,
  [1410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_LPAREN,
  [1417] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_LBRACE,
  [1424] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_EQ,
  [1431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
  [1438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [1445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
  [1452] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
  [1459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
  [1466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
  [1473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 30,
  [SMALL_STATE(9)] = 60,
  [SMALL_STATE(10)] = 90,
  [SMALL_STATE(11)] = 120,
  [SMALL_STATE(12)] = 150,
  [SMALL_STATE(13)] = 180,
  [SMALL_STATE(14)] = 210,
  [SMALL_STATE(15)] = 244,
  [SMALL_STATE(16)] = 274,
  [SMALL_STATE(17)] = 312,
  [SMALL_STATE(18)] = 348,
  [SMALL_STATE(19)] = 378,
  [SMALL_STATE(20)] = 427,
  [SMALL_STATE(21)] = 476,
  [SMALL_STATE(22)] = 525,
  [SMALL_STATE(23)] = 574,
  [SMALL_STATE(24)] = 623,
  [SMALL_STATE(25)] = 672,
  [SMALL_STATE(26)] = 715,
  [SMALL_STATE(27)] = 758,
  [SMALL_STATE(28)] = 801,
  [SMALL_STATE(29)] = 844,
  [SMALL_STATE(30)] = 887,
  [SMALL_STATE(31)] = 930,
  [SMALL_STATE(32)] = 973,
  [SMALL_STATE(33)] = 1016,
  [SMALL_STATE(34)] = 1059,
  [SMALL_STATE(35)] = 1095,
  [SMALL_STATE(36)] = 1131,
  [SMALL_STATE(37)] = 1154,
  [SMALL_STATE(38)] = 1179,
  [SMALL_STATE(39)] = 1202,
  [SMALL_STATE(40)] = 1225,
  [SMALL_STATE(41)] = 1247,
  [SMALL_STATE(42)] = 1265,
  [SMALL_STATE(43)] = 1290,
  [SMALL_STATE(44)] = 1315,
  [SMALL_STATE(45)] = 1340,
  [SMALL_STATE(46)] = 1365,
  [SMALL_STATE(47)] = 1390,
  [SMALL_STATE(48)] = 1400,
  [SMALL_STATE(49)] = 1410,
  [SMALL_STATE(50)] = 1417,
  [SMALL_STATE(51)] = 1424,
  [SMALL_STATE(52)] = 1431,
  [SMALL_STATE(53)] = 1438,
  [SMALL_STATE(54)] = 1445,
  [SMALL_STATE(55)] = 1452,
  [SMALL_STATE(56)] = 1459,
  [SMALL_STATE(57)] = 1466,
  [SMALL_STATE(58)] = 1473,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 7, 0, 5),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 7, 0, 5),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expression, 2, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expression, 2, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_infix_expression, 3, 0, 3),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_expression, 3, 0, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 11, 0, 6),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 11, 0, 6),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_hash_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_hash_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_hash_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_hash_repeat1, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 2),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 2),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, 0, 4),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, 0, 4),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_operator, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_operator, 1, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [242] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 2, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 3, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_monkey(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
